### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by hakluke** [hakluke/hakq#1]
Need to add timeouts on jobs. For example, if I run `ping 1.1.1.1` it will run forever, taking up a slot on a client.

**Comment by mzfr** [comment]
since we are executing the command like `exec.Command("/bin/sh", "-c", message).Output()` so maybe we can stick with linux [`timeout`](https://www.howtoforge.com/linux-timeout-command/) command	

If you want more `golang` specific way then I we can do something like:

```go
ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
defer cancel()

cmd := exec.CommandContext(ctx, "ping", "-c 4", "-i 1", "8.8.8.8")

out, err := cmd.Output()

if ctx.Err() == context.DeadlineExceeded {
    fmt.Println("Command timed out")
    return
}

fmt.Println("Output:", string(out))
if err != nil {
    fmt.Println("Non-zero exit code:", err)
}
```

I mean using `CommandContext`.

**Comment by hakluke** [comment]
Sounds good to me! Any chance you can put it in a PR?

**Comment by mzfr** [comment]
Yes I'll be making a PR for this but I was kind of asking it. I mean there are two options 
1) use linux timeout command 
2) use golang code 

Which method do you want to continue with?

**Comment by hakluke** [comment]
Oh I see what you mean! I think it would be best to go with the Golang method, it would be nice to make this platform independent at some point in the future (I know right now it calls bash, but that may change!)

**Comment by mzfr** [comment]
Cool I'll try to submit the PR as soon as possible :)
